services:
  - type: web
    name: vibr-backend
    env: python
    buildCommand: pip install -r backend/requirements-render.txt
    startCommand: cd backend && python main-simple.py
    healthCheckPath: /health
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false

  - type: web
    name: vibr-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://vibr-backend.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: Vibr 